# 应用服务 WEB 访问端口
server:
  port: 8888

# mysql数据库连接
spring:
  application:
    name: agr
  datasource:
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    #url:  jdbc:mysql://101.201.52.153:3306/agr?serverTimezone=GMT%2B8
    url:  jdbc:mysql://127.0.0.1:3306/agr?serverTimezone=GMT%2B8
    username: root
    password: agrzhnl2024


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

#logging:
#  # 日志配置文件地址 **不需要修改**
#  config: classpath:log4j.xml
#  file:
#    # 日志路径  **最后一级是文件名称**
#    path: log/${spring.application.name}
